path: ../datasets/coco
train: images/train
val: images/val

# número de classes
nc: 10

# nomes das classes na ordem (inglês — devem corresponder aos nomes do COCO filtrado)
names:
  [
    'person',
    'backpack',
    'chair',
    'bench',
    'laptop',
    'cell phone',
    'bottle',
    'book',
    'cup',
    'tv',
  ]
